SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES_SUM*PRICE)
FROM BOOK b
JOIN (SELECT BOOK_ID, SUM(SALES) as SALES_SUM
      FROM BOOK_SALES
      WHERE SALES_DATE >= '2022-01-01' and SALES_DATE < '2022-02-01'
      GROUP BY BOOK_ID) bs
ON b.BOOK_ID = bs.BOOK_ID
JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
GROUP BY a.AUTHOR_ID, CATEGORY
ORDER BY 1 asc, CATEGORY desc;
