WITH MILK_CART as (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
), YOGURT_CART as (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)



SELECT DISTINCT(mc.CART_ID)
FROM MILK_CART mc
JOIN YOGURT_CART yc
ON mc.CART_ID = yc.CART_ID