# SELECT e.ID
# FROM ECOLI_DATA e
# JOIN (SELECT e.ID
#     FROM ECOLI_DATA e
#     JOIN ECOLI_DATA p
#     ON p.ID = e.PARENT_ID) p
# ON e.PARENT_ID = p.ID
# ORDER BY 1 asc;

WITH RECURSIVE ECOLI_GEN as (
    SELECT ID, PARENT_ID, 1 as GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID is NULL
    UNION ALL
    SELECT e.ID, e.PARENT_ID, g.GEN+1
    FROM ECOLI_DATA e
    JOIN ECOLI_GEN g
    ON e.PARENT_ID = g.ID
    
)

SELECT ID
FROM ECOLI_GEN
WHERE GEN = 3
ORDER BY ID asc;