WITH ALL_SALES as (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE)

SELECT * 
FROM ALL_SALES
WHERE SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01'
ORDER BY 1 asc, 2 asc, 3 asc;