SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
JOIN ( SELECT FOOD_TYPE, MAX(FAVORITES) as MAX_FAVORITES
    FROM REST_INFO  
    GROUP BY FOOD_TYPE) f
ON r.FAVORITES = f.MAX_FAVORITES and r.FOOD_TYPE = f.FOOD_TYPE
ORDER BY 1 desc;