SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
FROM ANIMAL_INS ai
JOIN ANIMAL_OUTS ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE SEX_UPON_INTAKE like 'Intact%' and SEX_UPON_OUTCOME not like 'Intact%'
ORDER BY 1;