SELECT ri.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) "SCORE"
FROM REST_INFO ri
JOIN REST_REVIEW rr
ON ri.REST_ID = rr.REST_ID
WHERE ADDRESS like '서울%'
GROUP BY ri.REST_ID
ORDER BY 6 desc, 4 desc;