SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT(ui.USER_ID))
FROM USER_INFO ui
JOIN ONLINE_SALE os
ON ui.USER_ID = os.USER_ID
WHERE GENDER is not NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1 asc, 2 asc, 3 asc