SELECT year(SALES_DATE) as YEAR, 
    month(SALES_DATE) as MONTH, GENDER, count(DISTINCT o.USER_ID) as USERS
FROM ONLINE_SALE o
JOIN USER_INFO u
ON o.USER_ID = u.USER_ID
WHERE GENDER is not NULL
GROUP BY year(SALES_DATE), month(SALES_DATE), GENDER
ORDER BY 1,2,3