SELECT YEAR(SALES_DATE) as YEAR, 
    MONTH(SALES_DATE) as MONTH, 
    COUNT(DISTINCT ui.USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT ui.USER_ID) / (SELECT COUNT(*)
                                        FROM USER_INFO
                                        WHERE YEAR(JOINED) = 2021),
          1) AS PUCHASED_RATIO
FROM USER_INFO ui
JOIN ONLINE_SALE os
ON ui.USER_ID = os.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1 asc, 2 asc
