WITH RECURSIVE ECOLI_GENERATION as(
    SELECT ID, PARENT_ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID is NULL
    UNION ALL
    SELECT ed.ID, ed.PARENT_ID, GENERATION+1
    FROM ECOLI_DATA as ed
    JOIN ECOLI_GENERATION eg
    ON ed.PARENT_ID = eg.ID
)
SELECT COUNT(eg.ID) as COUNT, GENERATION
FROM ECOLI_GENERATION eg 
LEFT OUTER JOIN ECOLI_DATA ed
ON eg.ID = ed.PARENT_ID
WHERE ed.ID is NULL
GROUP BY GENERATION
ORDER BY GENERATION
