WITH AVAILABLE_CAR as (
    SELECT CAR_ID, 1 as AVAILABLE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT rh.CAR_ID, IF(ac.AVAILABLE is NULL, '대여 가능', '대여중') as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
LEFT OUTER JOIN AVAILABLE_CAR ac
ON rh.CAR_ID = ac.CAR_ID
GROUP BY CAR_ID
ORDER BY 1 desc
