SELECT fp.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT)
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
GROUP BY fp.PRODUCT_ID
ORDER BY 3 desc, 1 asc;