WITH HISTORY_DURATION as (
    SELECT HISTORY_ID, (DATEDIFF(END_DATE, START_DATE)+1) * DAILY_FEE as TOTAL_FEE, 
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE NULL
        END as DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
    JOIN CAR_RENTAL_COMPANY_CAR cc
    ON ch.CAR_ID = cc.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, FLOOR(TOTAL_FEE*(1-(COALESCE(DISCOUNT_RATE, 0)/100))) as FEE
FROM HISTORY_DURATION hd
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp
ON cp.CAR_TYPE = '트럭' and hd.DURATION_TYPE = cp.DURATION_TYPE
ORDER BY 2 desc, 1 desc
