WITH JULY_TOTAL as (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOT
    FROM JULY
    GROUP BY FLAVOR
)
SELECT fh.FLAVOR
FROM FIRST_HALF fh
JOIN JULY_TOTAL jt
ON fh.FLAVOR = jt.FLAVOR
ORDER BY TOTAL_ORDER+TOT desc
LIMIT 3