SELECT fh.FLAVOR
FROM FIRST_HALF fh
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOT
     FROM JULY
     GROUP BY FLAVOR) JULY
ON fh.FLAVOR = JULY.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(fh.TOTAL_ORDER)+JULY.TOT desc
LIMIT 3;
