SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
JOIN DOCTOR d
ON a.MDDR_ID = d.DR_ID
JOIN PATIENT p
ON a.PT_NO = p.PT_NO
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' and APNT_CNCL_YN = 'N' and a.MCDP_CD = "CS"
ORDER BY APNT_YMD