SELECT APNT_NO, PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT p
ON a.PT_NO = p.PT_NO
JOIN DOCTOR d
ON a.MDDR_ID = d.DR_ID
WHERE APNT_YMD >= '2022-04-13' and APNT_YMD < '2022-04-14'
    and a.APNT_CNCL_YN = 'N'
    and d.MCDP_CD = 'CS'
ORDER BY APNT_YMD asc;