WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR+1
    FROM HOUR_TABLE
    WHERE HOUR < 23
)

SELECT h.HOUR, COUNT(ANIMAL_ID)
FROM HOUR_TABLE h
LEFT JOIN ANIMAL_OUTS a
ON h.HOUR = HOUR(a.DATETIME)
GROUP BY h.HOUR
ORDER BY 1 asc;