WITH REVIEW_COUNT as (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) as CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
RANK_MEMBER as (
    SELECT * 
    FROM (
        SELECT MEMBER_ID, RANK() OVER (ORDER BY CNT desc) as RNK
        FROM REVIEW_COUNT
        ) as r
    WHERE RNK = 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE mp
JOIN REST_REVIEW rr
ON mp.MEMBER_ID = rr.MEMBER_ID
JOIN RANK_MEMBER rm
ON mp.MEMBER_ID = rm.MEMBER_ID
ORDER BY 3 asc, 2 asc

