WITH TOP_MEMBER as (
    SELECT rr.MEMBER_ID, MEMBER_NAME
    FROM REST_REVIEW rr
    JOIN MEMBER_PROFILE mp
    ON rr.MEMBER_ID = mp.MEMBER_ID
    GROUP BY rr.MEMBER_ID
    ORDER BY COUNT(rr.MEMBER_ID) desc
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW rr
JOIN TOP_MEMBER tm
ON rr.MEMBER_ID = tm.MEMBER_ID
ORDER BY 3 asc, 2 asc;