WITH TOP_MEMBER as (
    SELECT rr.MEMBER_ID, MEMBER_NAME,
        RANK() OVER (ORDER BY COUNT(rr.MEMBER_ID) desc) "RNK"
    FROM REST_REVIEW rr
    JOIN MEMBER_PROFILE mp
    ON rr.MEMBER_ID = mp.MEMBER_ID
    GROUP BY rr.MEMBER_ID
)

SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW rr
JOIN TOP_MEMBER tm
ON rr.MEMBER_ID = tm.MEMBER_ID
WHERE tm.RNK = 1
ORDER BY 3 asc, 2 asc;
