SELECT month(START_DATE) as MONTH, CAR_ID, count(HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE between '2022-08-01' and '2022-10-31'
    and CAR_ID in (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE between '2022-08-01' and '2022-10-31'
    GROUP BY CAR_ID
    HAVING count(*) >= 5
    
)
GROUP BY month(START_DATE), CAR_ID
ORDER BY 1, 2 desc