WITH SIZE_PER_YEAR as (
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT sy.YEAR, MAX_SIZE - SIZE_OF_COLONY as YEAR_DEV, ID
FROM ECOLI_DATA ed
JOIN SIZE_PER_YEAR sy
ON YEAR(ed.DIFFERENTIATION_DATE) = sy.YEAR
ORDER BY 1, 2