WITH MAX_LEN as (
    SELECT fi.FISH_TYPE, MAX(ni.FISH_NAME) as FISH_NAME, MAX(LENGTH) as LENGTH
    FROM FISH_INFO fi
    JOIN FISH_NAME_INFO ni
    ON fi.FISH_TYPE = ni.FISH_TYPE
    GROUP BY FISH_TYPE
)

SELECT ID, FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN MAX_LEN ml
ON fi.FISH_TYPE = ml.FISH_TYPE and fi.LENGTH = ml.LENGTH
ORDER BY 1

