SELECT fp.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT fp
JOIN (SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
     FROM FOOD_PRODUCT
     GROUP BY CATEGORY
     HAVING CATEGORY in ('과자', '국', '김치', '식용유')) mp
ON fp.CATEGORY = mp.CATEGORY and fp.PRICE = mp.MAX_PRICE
ORDER BY 2 desc;
