WITH MAX_VAL as (
    SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)

SELECT fp.CATEGORY, mv.MAX_PRICE, fp.PRODUCT_NAME
FROM FOOD_PRODUCT fp
JOIN MAX_VAL mv
ON fp.CATEGORY = mv.CATEGORY and fp.PRICE = mv.MAX_PRICE
ORDER BY 2 desc