WITH DEV_SKILLS AS (
    SELECT d.ID, GROUP_CONCAT(sc.NAME) as SKILLS, GROUP_CONCAT(DISTINCT(sc.CATEGORY)) as CATEGORIES
    FROM DEVELOPERS d
    JOIN SKILLCODES sc
    ON d.SKILL_CODE & sc.CODE
    GROUP BY d.ID
), DEV_GRADE as (
    SELECT ds.ID, CASE
        WHEN CATEGORIES LIKE '%Front End%' and SKILLS LIKE '%Python%' THEN 'A'
        WHEN SKILLS LIKE '%C#%' THEN 'B'
        WHEN CATEGORIES LIKE '%Front End%' THEN 'C'
        ELSE NULL
    END as GRADE
FROM DEVELOPERS s
JOIN DEV_SKILLS ds
ON s.ID = ds.ID
)


SELECT GRADE, d.ID, EMAIL
FROM DEVELOPERS d
JOIN DEV_GRADE dg
ON d.ID = dg.ID
WHERE GRADE is not NULL
ORDER BY 1, 2