name: Sync Java Files to Notion

on:
  push:
    branches:
      - main
    paths:
      - '**.java'

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 히스토리를 가져오도록 수정

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.java
          since_last_remote_commit: true # 마지막 원격 커밋 이후의 변경사항 확인

      - name: Debug changed files
        run: |
          echo "=== Debug Information ==="
          echo "Added files:"
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file"
          done

          echo "Modified files:"
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file"
          done

          echo "All changed files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @notionhq/client

      - name: Sync to Notion
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: node .github/scripts/sync-to-notion.js
