name: Sync Java Files to Notion

on:
  push:
    branches:
      - main
    paths:
      - '**.java'

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        run: |
          echo "All added files:"
          echo "${{ steps.changed-files.outputs.added_files }}"
          echo "All modified files:"
          echo "${{ steps.changed-files.outputs.modified_files }}"
          echo "All changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

          - name: Get diff for added files
          run: |
            # 추가된 파일 목록을 가져와서 diff를 찾습니다
            for file in ${{ steps.changed-files.outputs.added_files }}; do
              echo "Getting diff for: $file"
              git diff origin/main -- "$file" > "diff_$file.txt"  # diff를 파일로 저장
            done
            
            # 생성된 diff 파일들을 출력
            for file in ${{ steps.changed-files.outputs.added_files }}; do
              echo "Diff for $file:"
              cat "diff_$file.txt"
            done

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @notionhq/client

      - name: Sync to Notion
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run: node .github/scripts/sync-to-notion.js
