name: Sync Java Files to Notion

on:
  push:
    branches:
      - main
    paths:
      - '**.java'

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @notionhq/client

      - name: Sync to Notion
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node .github/scripts/sync-to-notion.js
