name: Post to Blog

on:
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run post.py
        run: |
          python .github/scripts/post.py
          echo "=== Debug: Listing md_output directory ==="
          ls -la $GITHUB_WORKSPACE/md_output
          echo "=== Debug: Checking if any .md files exist ==="
          find $GITHUB_WORKSPACE/md_output -name "*.md"

      - name: Checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: Sionparadox/Sionparadox.github.io
          token: ${{ secrets.MY_TOKEN}}
          path: blog

      - name: Copy new md file
        run: |
          echo "=== Debug: Before copying ==="
          ls -la $GITHUB_WORKSPACE/md_output
          cp $GITHUB_WORKSPACE/md_output/*.md blog/posts/Test/ || echo "No .md files found in md_output"
          echo "=== Debug: After copying ==="
          ls -la blog/posts/Test/

      - name: Commit & Push
        run: |
          cd blog
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add posts/Test/
          git commit -m "Add new solved problem post"
          git push
