name: Post to Blog

on:
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run post.py
        run: |
          python .github/scripts/post.py
          echo "=== Debug: Listing md_output directory ==="
          if [ ! -d "$GITHUB_WORKSPACE/md_output" ] || [ -z "$(ls -A $GITHUB_WORKSPACE/md_output)" ]; then
            echo "No MDX files generated. Exiting workflow."
            exit 0
          fi
          ls -la $GITHUB_WORKSPACE/md_output
          echo "=== Debug: Checking if any .mdx files exist ==="
          find $GITHUB_WORKSPACE/md_output -name "*.mdx"

      - name: Checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: Sionparadox/Sionparadox.github.io
          token: ${{ secrets.MY_TOKEN}}
          path: blog

      - name: Copy new mdx file
        run: |
          echo "=== Debug: Before copying ==="
          ls -la $GITHUB_WORKSPACE/md_output
          cp $GITHUB_WORKSPACE/md_output/*.mdx blog/posts/Problems/ || echo "No .mdx files found in md_output"
          echo "=== Debug: After copying ==="
          ls -la blog/posts/Problems/

      - name: Commit & Push
        run: |
          cd blog
          git config user.name "Sionparadox"
          git config user.email "sion9999@naver.com"
          git add posts/Problems/
          git commit -m "Add new solved problem post"
          git push
