name: Post to Blog

on:
  push:
    branches:
      - main

jobs:
  check-mdx:
    runs-on: ubuntu-latest
    outputs:
      has_mdx: ${{ steps.check_mdx.outputs.has_mdx }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check MDX files
        id: check_mdx
        run: |
          python .github/scripts/post.py
          echo "=== Debug: Listing md_output directory ==="
          if [ ! -d "$GITHUB_WORKSPACE/md_output" ] || [ -z "$(ls -A $GITHUB_WORKSPACE/md_output)" ]; then
            echo "No MDX files generated. Skipping blog update."
            echo "has_mdx=false" >> $GITHUB_OUTPUT
          else
            echo "MDX files found. Proceeding with blog update."
            echo "has_mdx=true" >> $GITHUB_OUTPUT
            ls -la $GITHUB_WORKSPACE/md_output
            echo "=== Debug: Checking if any .mdx files exist ==="
            find $GITHUB_WORKSPACE/md_output -name "*.mdx"
          fi

  update-blog:
    needs: check-mdx
    if: needs.check-mdx.outputs.has_mdx == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Copy MDX files
        run: |
          cp $GITHUB_WORKSPACE/md_output/*.mdx $GITHUB_WORKSPACE/

      - name: Checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: Sionparadox/Sionparadox.github.io
          token: ${{ secrets.MY_TOKEN}}
          path: blog

      - name: Copy new mdx file
        run: |
          echo "=== Debug: Before copying ==="
          ls -la $GITHUB_WORKSPACE
          cp $GITHUB_WORKSPACE/*.mdx blog/posts/Problems/ || echo "No .mdx files found"
          echo "=== Debug: After copying ==="
          ls -la blog/posts/Problems/

      - name: Commit & Push
        run: |
          cd blog
          git config user.name "Sionparadox"
          git config user.email "sion9999@naver.com"
          git add posts/Problems/
          git commit -m "Add new solved problem post"
          git push
